file=ejemplo.txt


all: ap1_objects ap1_mezcla
	@echo "Compilación y ejecución de la práctica"

clean:
	@echo "Limpiando..."

ap1_objects:
	@python3 cliente_servidor_ficheros.py

ap1_mezcla:
	@python3 cliente_servidor_mezcla.py $(file)
