

all: ap1_objects ap1_descriptores
	@echo "Compilación y ejecución de la práctica"

clean:
	@echo "Limpiando..."

ap1_objects:
	python3 cliente_servidor_ficheros.py

ap1_descriptores:
	python3 cliente_servidor_descriptores.py
