file=ejemplo.txt

all: ap1_servidor ap1_cliente
	@echo "Compilación y ejecución de la práctica"

clean:
	@echo "Limpiando..."

ap1_servidor:
	python3 servidor_ap1.py
ap1_cliente:
	python3 cliente_ap1.py $(file)
